// /* eslint-disable @next/next/no-img-element */
import { GetServerSideProps, type InferGetServerSidePropsType } from "next";
import Head from "next/head";
import Link from "next/link";
import { MyUploadButton } from "~/components/uploadButton";
// import { api } from "~/utils/api";
import { getImages } from "~/utils/ipfs";
import { getToken } from "next-auth/jwt";
import { getSession } from "next-auth/react";
import { prisma } from "~/server/db";
import { userAgent } from "next/server";
import { useState } from "react";
import { CreatorForm } from "~/components/creator-form";

export const getServerSideProps: GetServerSideProps = async (context) => {
  const asyncImageIterator = await getImages();
  const result = [];
  for await (const item of asyncImageIterator) {
    result.push(item.cid.toString());
  }

  // Get User role
  const session = await getSession(context);
  const token = await getToken({ req: context.req });
  const user = await prisma.user.findFirst({
    where: {
      addressETH: token?.sub,
    },
  });
  return {
    props: {
      images: result,
      user: {...user, createdAt: null},
    },
  };
};

const Home = ({
  images,
  user,
}: InferGetServerSidePropsType<typeof getServerSideProps>) => {
  const [showForm, setShowForm] = useState(false);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="absolute flex h-screen w-full flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex h-full flex-col items-center justify-center gap-12 px-4 py-16">
          {user?.role != "creator" && (
            <button name="becomeCreator" className="btn btn-primary" onClick={() => setShowForm(true)}>
              Register as Creator
            </button>
          )}
          {showForm && <CreatorForm/>}
        </div>
      </main>
    </>
  );
};

export default Home;
